// Server generated by gomarvin, v0.10.x
// Repo : https://github.com/tompston/gomarvin
// Docs : https://gomarvin.pages.dev/docs

package main

import (
	"context"
	"log"
	"xtuples/internal/api/v1/server"
	"xtuples/pkg/app"
)

func main() {

	// initialize the environment
	app, err := app.NewApp(context.Background())
	if err != nil {
		log.Fatal(err)
	}
	defer app.Exit(context.Background())

	server.NewServer(app).Start()
}
