// Code generated by gomarvin, v0.10.x. DO NOT EDIT.
// Rename the current file, remove upper comment
// and replace __ to save changes!

package exec_module

import (
	"fmt"
	res "xtuples/internal/api/response"

	"github.com/gin-gonic/gin"

	"xtuples/pkg/validate"
)

const (
	__ExecUrl = "/exec"
)

func Router__(app *gin.RouterGroup) {
	app.POST(__ExecUrl, __Exec)
}

// POST URL/exec
func __Exec(c *gin.Context) {

	// validate the sent body
	payload := new(ExecBody)
	if err := validate.RequestBody(c, payload); err != nil {
		res.Response(c, 400, err, res.FailedPayloadValidationMessage)
		return
	}

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "")
}

// Placeholder function to be replaced in the controllers after codegen.
// Usually replaced with the function which returns the data from the db.
func placeholderFunc() (struct{}, error) {
	var placeholder struct{}
	return placeholder, nil
}
