// Code generated by gomarvin, v0.10.x. DO NOT EDIT.
// Rename the current file, remove upper comment
// and replace __ to save changes!

package cron_module

import (
	"fmt"
	res "xtuples/internal/api/response"

	"github.com/gin-gonic/gin"

	"strconv"

	"xtuples/pkg/validate"
)

const (
	__GetCronsUrl   = "/cron"
	__GetCronUrl    = "/cron/:id"
	__CreateCronUrl = "/cron"
	__DeleteCronUrl = "/cron/:id"
	__UpdateCronUrl = "/cron/:id"
)

func Router__(app *gin.RouterGroup) {
	app.GET(__GetCronsUrl, __GetCrons)
	app.GET(__GetCronUrl, __GetCron)
	app.POST(__CreateCronUrl, __CreateCron)
	app.DELETE(__DeleteCronUrl, __DeleteCron)
	app.PUT(__UpdateCronUrl, __UpdateCron)
}

// GET URL/cron
func __GetCrons(c *gin.Context) {

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "", res.PaginationLinks{})
}

// GET URL/cron/[id:int]
func __GetCron(c *gin.Context) {

	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		res.Response(c, 400, nil, res.ParamIsNotIntMessage)
		return
	}
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "")
}

// POST URL/cron
func __CreateCron(c *gin.Context) {

	// validate the sent body
	payload := new(CreateCronBody)
	if err := validate.RequestBody(c, payload); err != nil {
		res.Response(c, 400, err, res.FailedPayloadValidationMessage)
		return
	}

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "")
}

// DELETE URL/cron/[id:int]
func __DeleteCron(c *gin.Context) {

	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		res.Response(c, 400, nil, res.ParamIsNotIntMessage)
		return
	}
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "")
}

// PUT URL/cron/[id:int]
func __UpdateCron(c *gin.Context) {

	// validate the sent body
	payload := new(UpdateCronBody)
	if err := validate.RequestBody(c, payload); err != nil {
		res.Response(c, 400, err, res.FailedPayloadValidationMessage)
		return
	}

	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		res.Response(c, 400, nil, res.ParamIsNotIntMessage)
		return
	}
	_ = id

	// replace the function to return the data from the db
	data, err := placeholderFunc()
	if err != nil {
		fmt.Printf("Error occured while calling db: %v\n", err) // replace with logger
		res.Response(c, 400, nil, res.FailedDbConnMessage)
		return
	}

	res.Response(c, 200, data, "")
}

// Placeholder function to be replaced in the controllers after codegen.
// Usually replaced with the function which returns the data from the db.
func placeholderFunc() (struct{}, error) {
	var placeholder struct{}
	return placeholder, nil
}
